### ISSUE TITLE
Possible SQL Injection?

### ISSUE THREAD

**Issue by neovintage** [fridgerator/crecto#2]
Was looking through the SQL generation code and I couldn't tell. Are the parameters getting sanitized before building the query?

**Comment by fridgerator** [comment]
I was actually just looking at this today, currently I'm not doing anything.  However it should be a priority.

[crystal-pg](https://github.com/will/crystal-pg) appears to have some method to sanitize parameters, but only if you used parameterized queries (which is not being used).

**Comment by fridgerator** [comment]
Moving towards parameterized queries, should have a fix in later today.
