### ISSUE TITLE
update travis config to test both postgres and mysql

### ISSUE THREAD

**Issue by fridgerator** [fridgerator/crecto#26]

**Comment by fridgerator** [comment]
couple of links:
* [https://ariejan.net/2016/04/15/hanami-and-multi-database-testing-with-travis/](https://ariejan.net/2016/04/15/hanami-and-multi-database-testing-with-travis/)

* [http://tomdallimore.com/blog/how-to-run-with-rails-configure-travis-ci-to-use-multiple-databases/](http://tomdallimore.com/blog/how-to-run-with-rails-configure-travis-ci-to-use-multiple-databases/)

**Comment by neovintage** [comment]
see #40
