### ISSUE TITLE
JSON / JSONB data types for postgres

### ISSUE THREAD

**Issue by neovintage** [fridgerator/crecto#27]
Any ideas on how to provide this or if it's possible already?

**Comment by fridgerator** [comment]
I had thought about implementing something like ecto's [embeds_one](https://hexdocs.pm/ecto/Ecto.Schema.html#embeds_one/3) and [embeds_many](https://hexdocs.pm/ecto/Ecto.Schema.html#embeds_many/3)

[https://robots.thoughtbot.com/embedding-elixir-structs-in-ecto-models](https://robots.thoughtbot.com/embedding-elixir-structs-in-ecto-models)

**Comment by fridgerator** [comment]
It might make sense to first implement jsonb field types for models?

**Comment by neovintage** [comment]
would embeds_one and embeds_many work for other databases besides postgres?

**Comment by fridgerator** [comment]
I don't believe it would work with MySQL
