### ISSUE TITLE
Postgres Adapter: Invalid query being generated

### ISSUE THREAD

**Issue by neovintage** [fridgerator/crecto#33]
I was using a where clause and the sql being generated by the Query class is invalid. 

```
query = Crecto::Repo::Query.where("settings.user_id = $1", [1])
settings = Crecto::Repo.all(UserSetting, query)
```

Generated SQL:
```
SELECT user_settings.* FROM user_settings WHEREuser_settings.user_id = $1
```

Its missing spacing after the WHERE.

As a side note, it'd be great if we had some kind of logging middleware so that you could see what's being generated by crecto.

**Comment by neovintage** [comment]
@fridgerator Was thinking about how to catch this in testing and I spiked this out:

https://github.com/neovintage/crecto/blob/query-spec/spec/adapters/postgres_adapter_spec.cr

What do you think about that? I could create a PR for postgres that checks the output of the SQL statements for the adapter.

**Comment by fridgerator** [comment]
@neovintage WOOPS!  tests must not be covering that case

Yeah I think that looks like a good solution.  @metacortex just made a PR #34 for the missing space after the `WHERE` for the mysql adapter.  So maybe its the same fix in the psql adapter.

Also just a heads up, I refactored the adapters to use a `BaseAdapter` module.  I think tonight I will finish that up and merge it into master, so if you want basing off of [adapters_refactor](fridgerator/crecto/tree/adapters_refactor) might be easier?

**Comment by fridgerator** [comment]
@neovintage  #36

**Comment by neovintage** [comment]
@fridgerator sweet. yeah when you get the adapter refactor in, I'll rebase my branch and add some more specific testing toward the generated sql. Then I think we can fix this.

**Comment by fridgerator** [comment]
@neovintage Its merged.  Thanks for your help!

**Comment by neovintage** [comment]
@fridgerator quick on the trigger! thanks
