### ISSUE TITLE
Use crystal-db

### ISSUE THREAD

**Issue by asterite** [fridgerator/crecto#4]
Eventually you should consider using https://github.com/crystal-lang/crystal-db as a dependency, because that's what all drivers will use, and then very little work will be needed in each adapter. [There's a pending PR in crystal-pg](https://github.com/will/crystal-pg/pull/60) but it will eventually be merged.

**Comment by fridgerator** [comment]
Thanks @asterite, I am already planning on using it I am just waiting for that PR :)
