### ISSUE TITLE
Design Question on `Crecto::Repo.all`

### ISSUE THREAD

**Issue by neovintage** [fridgerator/crecto#43]
Why throw a NoResults error when the query comes back empty? Is it possible to pass something like an empty array of the type?

I'm wondering what your take is on using exceptions to communicate a non-error state.

**Comment by fridgerator** [comment]
`Repo.all` should be returning an empty array if none are found

`Repo.get` is throwing `NoResults` error, in the same way active record does

I looks like Ecto though `#get` returns nil, but provides a `#get!` which throws an error if none are found

**Comment by fridgerator** [comment]
I liked the idea of `#get` throwing the exception and not returning something that is nilable (return type is the object class) so the user doesn't have to do the `nil?` or `not_nil!` check.

But I'm open to suggestions

**Comment by metacortex** [comment]
The convention of `method_name!` throwing error is comfortable to me.

**Comment by fridgerator** [comment]
I like that pattern as well, what do you think @neovintage
