### ISSUE TITLE
[FR] Cannot input an array into the validate_length function

### ISSUE THREAD

**Issue by rishavs** [fridgerator/crecto#51]
currently this works;
`validate_length :title, min: 5, max: 255`
but this doesnt.
`validate_length [:slug, :thumb, :link, :title], min: 5, max: 255`

However, other validations like validate_format, validate_inclusions etc accept arrays.

**Comment by fridgerator** [comment]
This was added a few days ago in #44, I haven't made a new release since then.  I can make one real quick though, we have enough features / fixes waiting.

**Comment by fridgerator** [comment]
cheers: https://github.com/fridgerator/crecto/releases/tag/v0.4.2 🎉

**Comment by rishavs** [comment]
thanks!
