### ISSUE TITLE
Issue with foreign keys

### ISSUE THREAD

**Issue by Zhomart** [fridgerator/crecto#55]
1. In the specs we have two connected models `User` with field `id : PkValue`, where `PkValue` is `Int32 | Int64` and model `Post` with field `user_id : Int32`. It's in `spec/spec_helper.cr:172`.
Should we users to force to provide correct types? *Right now I had issue with this incompatibility.*

2. In the macro `belongs_to` https://github.com/fridgerator/crecto/blob/master/src/crecto/schema/belongs_to.cr#L25 we have `@{{foreign_key.id}} = val.pkey_value.as(Int32)`. Instead of `Int32` it should be type of `foreign_key`. But I don't know how to get the type.
How should we deal with this?

**Comment by fridgerator** [comment]
Thanks for pointing this out, I've run into issues with incompatibility this as well.

Check out this PR: https://github.com/fridgerator/crecto/compare/merge_number_field_types?expand=1

I already have a `PkeyValue` alias in crecto.cr that is just an alias to `Int32 | Int64 | Nil`.  I was already changing Int64 field types to PkeyValue in schema.cr, so in this PR I'm also forcing Int32 to PkeyValue as well.

Let me now what you think.

**Comment by Zhomart** [comment]
That looks good. 
But it doesn't fix issue with `belongs_to`, we need to get type of `@{{foreign_key.id}}` somehow.

**Comment by fridgerator** [comment]
It should always be `PkeyValue` I think [link](https://github.com/fridgerator/crecto/blob/merge_number_field_types/src/crecto/schema/belongs_to.cr#L25)

**Comment by Zhomart** [comment]
This one should be `PkeyValue` https://github.com/fridgerator/crecto/blob/master/spec/spec_helper.cr#L166
too, is that right? I was having problem particular with this one.

**Comment by fridgerator** [comment]
Correct, I believe that is changed in my branch also.  Also because of this pr #50, if you declare `belongs_to` the foreign key is set for you now, so those fields are optional.

Let me merge my branch to master, that might make it easier to work with.  If you still run into problems afterwords let me know :)

**Comment by fridgerator** [comment]
Ok I merged the PR https://github.com/fridgerator/crecto/pull/56, its in master now

**Comment by Zhomart** [comment]
I'll close it, as the issue was fixed.
